/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programafacultad;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dhani
 */
public class FrmFacultad extends javax.swing.JFrame {

    //declaration of ArrayList that are part of the 
    //structure to keep temporary data, if the application is closed the data will be lost.
    ArrayList<Profesor> dbProfesores = new ArrayList<>();
    ArrayList<Servicio> dbEmpServicio = new ArrayList<>();
    ArrayList<Estudiante> dbEstudiantes = new ArrayList<>();

    //method addDbProfessors receives an object and adds it to the arraylistDb
    public boolean addDbProfesores(Profesor newProfesor) {
        if (newProfesor == null) {
            return false;
        }
        if (!this.dbProfesores.contains(newProfesor)) {
            this.dbProfesores.add(newProfesor);
            return true;
        } else {
            return false;
        }
    }
    //method addDbEmServicio receives an object and adds it to the arraylistDb
    public boolean addDbEmServicio(Servicio newServicio) {
        if (newServicio == null) {
            return false;
        }
        if (!this.dbEmpServicio.contains(newServicio)) {
            this.dbEmpServicio.add(newServicio);
            return true;
        } else {
            return false;
        }
    }
    //method addDbEstudiante receives an object and adds it to the arraylistDb
    public boolean addDbEstudiante(Estudiante newEstudiante) {
        if (newEstudiante == null) {
            return false;
        }
        if (!this.dbEstudiantes.contains(newEstudiante)) {
            this.dbEstudiantes.add(newEstudiante);
            return true;
        } else {
            return false;
        }
    }
    //this function return all the tempDb
    public ArrayList<Profesor> listarProfesores() {
        return dbProfesores;
    }
    //this function return all the tempDb
    public ArrayList<Servicio> listarServicio() {
        return dbEmpServicio;
    }
    //this function return all the tempDb
    public ArrayList<Estudiante> listarEstudiante() {

        return dbEstudiantes;
    }
    //this function just clear fields, filling them with and empty string
    public void limpiar() {
        //all profesor
        txt_nomb.setText("");
        txt_apell_edit.setText("");
        txt_incor_edit.setText("01/01/2000");
        txt_depto_edit.setText("");
        txt_desp_edit.setText("");
        txt_ecivil_edit.setText("");
        txt_nomb_edit.setText("");
        txt_incor_edit.setText("");
        txt_nomb.setText("");
        txt_apell.setText("");
        txt_id.setText("");
        txt_incor.setText("01/01/2000");
        txt_depto.setText("");
        txt_desp.setText("");
        txt_ecivil.setText("");
        //all empleado servicio
        txt_ape_srv.setText("");
        txt_desp_srv.setText("");
        txt_ecivil_srv.setText("");
        txt_id_srv.setText("");
        txt_incor.setText("01/01/2000");
        txt_nom_srv.setText("");
        txt_sec_srv.setText("");
        txt_ape_srv_edit.setText("");
        txt_desp_srv_edit.setText("");
        txt_ecivil_srv_edit.setText("");
        txt_id_srv_edit.setText("");
        txt_incor_srv_edit.setText("");
        txt_sec_srv_edit.setText("");
        //all estudiante
        txt_idEst_edit.setText("");
        txt_apellEst_edit.setText("");
        txt_cursoEst_edit.setText("");
        txt_ecivilEst_edit.setText("");
        txt_nombEst_edit.setText("");
        txt_cursoEst_edit.setText("");
        txt_idEst.setText("");
        txt_nombEst.setText("");
        txt_apellEst.setText("");
        txt_ecivilEst.setText("");
    }

    /**
     * Creates new form jfrm_facultad
     */
    public FrmFacultad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_desp = new javax.swing.JTextField();
        txt_depto = new javax.swing.JTextField();
        txt_nomb = new javax.swing.JTextField();
        txt_apell = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        txt_incor = new javax.swing.JTextField();
        txt_ecivil = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tabla = new javax.swing.JTable();
        btn_listarProfe = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_editarProfe = new javax.swing.JButton();
        btn_buscaEdit = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txt_id_edit = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_desp_edit = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_depto_edit = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_nomb_edit = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_apell_edit = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_incor_edit = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txt_ecivil_edit = new javax.swing.JTextField();
        btn_limpiar_edit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_id_srv = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_desp_srv = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_sec_srv = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_nom_srv = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_ape_srv = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_incor_srv = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txt_ecivil_srv = new javax.swing.JTextField();
        btn_agregar_srv = new javax.swing.JButton();
        btn_limpiar_srv = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_tablaSrv = new javax.swing.JTable();
        btn_listarSrv = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txt_id_srv_edit = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txt_desp_srv_edit = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txt_sec_srv_edit = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txt_nom_srv_edit = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txt_ape_srv_edit = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txt_incor_srv_edit = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txt_ecivil_srv_edit = new javax.swing.JTextField();
        btn_busca_srv_Edit = new javax.swing.JButton();
        btn_editar_srv = new javax.swing.JButton();
        btn_limpiar_edit1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        txt_idEst = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txt_cursoEst = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txt_nombEst = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txt_apellEst = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txt_ecivilEst = new javax.swing.JTextField();
        btn_agregarEst = new javax.swing.JButton();
        btn_limpiarEst = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btn_listarEst = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_tablaEst = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        txt_idEst_edit = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txt_cursoEst_edit = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txt_nombEst_edit = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txt_apellEst_edit = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txt_ecivilEst_edit = new javax.swing.JTextField();
        btn_buscaEst_edit = new javax.swing.JButton();
        btn_editarEst = new javax.swing.JButton();
        btn_limpiar_edit2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor de Factultad");
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel2.setText("Departamento");

        jLabel3.setText("Despacho");

        jLabel4.setText("Nombre");

        jLabel5.setText("Apellido");

        jLabel6.setText("Estado Civil");

        jLabel7.setText("Cedula");

        jLabel8.setText("Fecha ingreso ");

        txt_desp.setPreferredSize(new java.awt.Dimension(20, 24));

        txt_depto.setPreferredSize(new java.awt.Dimension(20, 24));
        txt_depto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_deptoActionPerformed(evt);
            }
        });

        txt_nomb.setPreferredSize(new java.awt.Dimension(20, 24));

        txt_apell.setPreferredSize(new java.awt.Dimension(20, 24));

        txt_id.setPreferredSize(new java.awt.Dimension(20, 24));

        txt_incor.setText("01/01/2000");
        txt_incor.setPreferredSize(new java.awt.Dimension(20, 24));

        txt_ecivil.setPreferredSize(new java.awt.Dimension(20, 24));

        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_depto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                            .addComponent(txt_nomb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_apell, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_incor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_ecivil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_desp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_agregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_limpiar)))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_desp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_depto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nomb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_apell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_incor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ecivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar)
                    .addComponent(btn_limpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear Profesor", jPanel1);

        tbl_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_tabla);

        btn_listarProfe.setText("Listar");
        btn_listarProfe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listarProfeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_listarProfe)
                .addGap(257, 257, 257))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_listarProfe))
        );

        jTabbedPane1.addTab("Listar Profesor", jPanel2);

        btn_editarProfe.setText("Editar");
        btn_editarProfe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarProfeActionPerformed(evt);
            }
        });

        btn_buscaEdit.setText("Buscar");
        btn_buscaEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscaEditActionPerformed(evt);
            }
        });

        jLabel15.setText("Cedula");

        txt_id_edit.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel16.setText("Despacho");

        txt_desp_edit.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel17.setText("Departamento");

        txt_depto_edit.setPreferredSize(new java.awt.Dimension(20, 24));
        txt_depto_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_depto_editActionPerformed(evt);
            }
        });

        jLabel18.setText("Nombre");

        txt_nomb_edit.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel19.setText("Apellido");

        txt_apell_edit.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel20.setText("Fecha ingreso ");

        txt_incor_edit.setEditable(false);
        txt_incor_edit.setText("01/01/2000");
        txt_incor_edit.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel21.setText("Estado Civil");

        txt_ecivil_edit.setPreferredSize(new java.awt.Dimension(20, 24));

        btn_limpiar_edit.setText("Limpiar");
        btn_limpiar_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiar_editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(btn_buscaEdit)
                .addGap(18, 18, 18)
                .addComponent(btn_editarProfe)
                .addGap(18, 18, 18)
                .addComponent(btn_limpiar_edit)
                .addGap(160, 160, 160))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel16)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18)
                        .addComponent(jLabel19)
                        .addComponent(jLabel21)
                        .addComponent(jLabel15)
                        .addComponent(jLabel20))
                    .addGap(61, 61, 61)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_depto_edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_nomb_edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_apell_edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_id_edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_incor_edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_ecivil_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_desp_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(24, 24, 24)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(239, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_buscaEdit)
                    .addComponent(btn_editarProfe)
                    .addComponent(btn_limpiar_edit))
                .addGap(15, 15, 15))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_id_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(txt_desp_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(txt_depto_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_nomb_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_apell_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_incor_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_ecivil_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21))
                    .addContainerGap(62, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Editar Profesor", jPanel3);

        jLabel9.setText("Cedula");

        txt_id_srv.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel10.setText("Despacho");

        txt_desp_srv.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel11.setText("Seccion");

        txt_sec_srv.setPreferredSize(new java.awt.Dimension(20, 24));
        txt_sec_srv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sec_srvActionPerformed(evt);
            }
        });

        jLabel12.setText("Nombre");

        txt_nom_srv.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel13.setText("Apellido");

        txt_ape_srv.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel14.setText("Fecha ingreso ");

        txt_incor_srv.setText("01/01/2000");
        txt_incor_srv.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel22.setText("Estado Civil");

        txt_ecivil_srv.setPreferredSize(new java.awt.Dimension(20, 24));

        btn_agregar_srv.setText("Agregar");
        btn_agregar_srv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_srvActionPerformed(evt);
            }
        });

        btn_limpiar_srv.setText("Limpiar");
        btn_limpiar_srv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiar_srvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel22)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_sec_srv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                            .addComponent(txt_nom_srv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_ape_srv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_id_srv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_incor_srv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_ecivil_srv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_desp_srv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_agregar_srv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_limpiar_srv)))
                .addGap(30, 30, 30))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id_srv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_desp_srv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_sec_srv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nom_srv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ape_srv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_incor_srv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ecivil_srv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar_srv)
                    .addComponent(btn_limpiar_srv))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear Empleado Servicio", jPanel4);

        tbl_tablaSrv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbl_tablaSrv);

        btn_listarSrv.setText("Listar");
        btn_listarSrv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listarSrvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_listarSrv)
                .addGap(257, 257, 257))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_listarSrv))
        );

        jTabbedPane1.addTab("Listar Empleado Servicio", jPanel5);

        jLabel23.setText("Cedula");

        txt_id_srv_edit.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel24.setText("Despacho");

        txt_desp_srv_edit.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel25.setText("Seccion");

        txt_sec_srv_edit.setPreferredSize(new java.awt.Dimension(20, 24));
        txt_sec_srv_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sec_srv_editActionPerformed(evt);
            }
        });

        jLabel26.setText("Nombre");

        txt_nom_srv_edit.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel27.setText("Apellido");

        txt_ape_srv_edit.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel28.setText("Fecha ingreso ");

        txt_incor_srv_edit.setEditable(false);
        txt_incor_srv_edit.setText("01/01/2000");
        txt_incor_srv_edit.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel29.setText("Estado Civil");

        txt_ecivil_srv_edit.setPreferredSize(new java.awt.Dimension(20, 24));

        btn_busca_srv_Edit.setText("Buscar");
        btn_busca_srv_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_busca_srv_EditActionPerformed(evt);
            }
        });

        btn_editar_srv.setText("Editar");
        btn_editar_srv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editar_srvActionPerformed(evt);
            }
        });

        btn_limpiar_edit1.setText("Limpiar");
        btn_limpiar_edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiar_edit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(btn_busca_srv_Edit)
                .addGap(18, 18, 18)
                .addComponent(btn_editar_srv)
                .addGap(18, 18, 18)
                .addComponent(btn_limpiar_edit1)
                .addGap(169, 169, 169))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel24)
                        .addComponent(jLabel25)
                        .addComponent(jLabel26)
                        .addComponent(jLabel27)
                        .addComponent(jLabel29)
                        .addComponent(jLabel23)
                        .addComponent(jLabel28))
                    .addGap(61, 61, 61)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_sec_srv_edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                        .addComponent(txt_nom_srv_edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_ape_srv_edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_id_srv_edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_incor_srv_edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_ecivil_srv_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_desp_srv_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(24, 24, 24)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 254, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_busca_srv_Edit)
                    .addComponent(btn_editar_srv)
                    .addComponent(btn_limpiar_edit1)))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_id_srv_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(txt_desp_srv_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(txt_sec_srv_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_nom_srv_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_ape_srv_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_incor_srv_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_ecivil_srv_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel29))
                    .addContainerGap(37, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Editar Empleado Servicio", jPanel6);

        jLabel30.setText("Cedula");

        txt_idEst.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel31.setText("Curso");

        txt_cursoEst.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel32.setText("Nombre");

        txt_nombEst.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel33.setText("Apellido");

        txt_apellEst.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel34.setText("Estado Civil");

        txt_ecivilEst.setPreferredSize(new java.awt.Dimension(20, 24));

        btn_agregarEst.setText("Agregar");
        btn_agregarEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarEstActionPerformed(evt);
            }
        });

        btn_limpiarEst.setText("Limpiar");
        btn_limpiarEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarEstActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_idEst, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .addComponent(txt_cursoEst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_ecivilEst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_apellEst, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_nombEst, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap(404, Short.MAX_VALUE)
                    .addComponent(btn_agregarEst)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btn_limpiarEst)
                    .addGap(24, 24, 24)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_idEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cursoEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_apellEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ecivilEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(224, 224, 224)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_agregarEst)
                        .addComponent(btn_limpiarEst))
                    .addContainerGap(30, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Crear Estudiante", jPanel7);

        btn_listarEst.setText("Listar");
        btn_listarEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listarEstActionPerformed(evt);
            }
        });

        tbl_tablaEst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tbl_tablaEst);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(btn_listarEst)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_listarEst)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Listar Estudiante", jPanel8);

        jLabel35.setText("Cedula");

        txt_idEst_edit.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel36.setText("Curso");

        txt_cursoEst_edit.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel37.setText("Nombre");

        txt_nombEst_edit.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel38.setText("Apellido");

        txt_apellEst_edit.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel39.setText("Estado Civil");

        txt_ecivilEst_edit.setPreferredSize(new java.awt.Dimension(20, 24));

        btn_buscaEst_edit.setText("Buscar");
        btn_buscaEst_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscaEst_editActionPerformed(evt);
            }
        });

        btn_editarEst.setText("Editar");
        btn_editarEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarEstActionPerformed(evt);
            }
        });

        btn_limpiar_edit2.setText("Limpiar");
        btn_limpiar_edit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiar_edit2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_buscaEst_edit)
                .addGap(18, 18, 18)
                .addComponent(btn_editarEst)
                .addGap(18, 18, 18)
                .addComponent(btn_limpiar_edit2)
                .addGap(158, 158, 158))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_idEst_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_cursoEst_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_ecivilEst_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_apellEst_edit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_nombEst_edit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_idEst_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cursoEst_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombEst_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_apellEst_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ecivilEst_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_buscaEst_edit)
                    .addComponent(btn_editarEst)
                    .addComponent(btn_limpiar_edit2))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Editar Estudiante", jPanel9);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setText("Programa Facultad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_deptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_deptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_deptoActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
        Profesor profe = null;
        try {
            String nombre = txt_nomb.getText();
            String apellido = txt_apell.getText();
            String cedula = txt_id.getText();
            String ecivil = txt_ecivil.getText();
            Date fechaIncorp = new SimpleDateFormat("dd/MM/yyyy").parse(txt_incor.getText());
            Departamento depto = new Departamento(txt_depto.getText());
            Despacho despacho = new Despacho(txt_desp.getText());
            if (!"".equals(nombre) && !"".equals(apellido) && !"".equals(cedula) && !"".equals(ecivil)) {
                //Profesor(Departamento depto, Despacho despacho, Date fechaIncor, String id, String nombre, String apellido, String eCivil, despacho, fechaIncor, id, nombre, apellido, eCivil);
                profe = new Profesor(depto, despacho, fechaIncorp, cedula, nombre, apellido, ecivil);
            }
            if (addDbProfesores(profe)) {
                JOptionPane.showMessageDialog(rootPane, "Profesor guardado");
                limpiar();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede guardar");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error, verifique que la fecha u otros campos estén correctos" + e);
        }
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_listarProfeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listarProfeActionPerformed
        // TODO add your handling code here:
        ArrayList<Profesor> datosProfesor = listarProfesores();
        DefaultTableModel model;
        //Departamento depto, Despacho despacho, Date fechaIncor, String id, String nombre, String apellido, String eCivil
        String[] columnas = {"id", "nombre", "apellido", "eCivil", "dpto", "desp", "incorp"};
        model = new DefaultTableModel(null, columnas);
        String[] filas = new String[7];
        for (Profesor profe : datosProfesor) {
            filas[0] = profe.getId();
            filas[1] = profe.getNombre();
            filas[2] = profe.getApellido();
            filas[3] = profe.geteCivil();
            filas[4] = profe.devolverDpto();
            filas[5] = profe.devolverDesp();
            filas[6] = String.valueOf(profe.getFechaIncor());
            model.addRow(filas);
        }
        tbl_tabla.setModel(model);
    }//GEN-LAST:event_btn_listarProfeActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_editarProfeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarProfeActionPerformed
        // TODO add your handling code here:
        int index = 0;
        Profesor profesorEncontrado = null;
        String cedBuscar = txt_id_edit.getText();
        for (Profesor profe : dbProfesores) {
            if (profe.getId().equals(cedBuscar)) {
                System.out.println(index);
                profesorEncontrado = profe;
                break;
            }
            index++;
        }
        if (profesorEncontrado != null) {
            Departamento depto;
            depto = new Departamento(txt_depto_edit.getText());
            Despacho desp;
            desp = new Despacho(txt_desp_edit.getText());
            try {
                Date fincor = new SimpleDateFormat("dd/MM/yyyy").parse(txt_incor_edit.getText());
                String idEditar = txt_id_edit.getText();
                String nomEditar = txt_nomb_edit.getText();
                String apeEditar = txt_apell_edit.getText();
                String estCivil = txt_ecivil_edit.getText();
                //(Departamento , Despacho , Date fechaIncor,  id,  nombre,  apellido,  eCivil
                dbProfesores.set(index, new Profesor(depto, desp, fincor, idEditar, nomEditar, apeEditar, estCivil));
                JOptionPane.showMessageDialog(rootPane, "Profesor Editado Correctamente");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error, verifique que la fecha u otros campos estén correctos" + e);
            }
        }
        limpiar();
    }//GEN-LAST:event_btn_editarProfeActionPerformed

    private void txt_depto_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_depto_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_depto_editActionPerformed

    private void btn_limpiar_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiar_editActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btn_limpiar_editActionPerformed

    private void btn_buscaEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscaEditActionPerformed
        // TODO add your handling code here:

        Profesor profesorEncontrado = null;
        String cedBuscar = txt_id_edit.getText();
        for (Profesor profe : dbProfesores) {
            if (profe.getId().equals(cedBuscar)) {
                profesorEncontrado = profe;
                break;
            }
        }
        if (profesorEncontrado != null) {
            txt_apell_edit.setText(profesorEncontrado.getApellido());
            txt_depto_edit.setText(profesorEncontrado.devolverDpto());
            txt_desp_edit.setText(profesorEncontrado.devolverDesp());
            txt_ecivil_edit.setText(profesorEncontrado.geteCivil());
            txt_nomb_edit.setText(profesorEncontrado.getNombre());
            txt_incor_edit.setText(String.valueOf(profesorEncontrado.getFechaIncor()));
        } else {
            JOptionPane.showMessageDialog(rootPane, "No se encuentra ese id");
        }

    }//GEN-LAST:event_btn_buscaEditActionPerformed

    private void txt_sec_srvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sec_srvActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        int index = 0;
        Servicio serviEncontrado = null;
        String cedSrvBuscar = txt_id_edit.getText();
        for (Servicio servi : dbEmpServicio) {
            if (servi.getId().equals(cedSrvBuscar)) {
                System.out.println(index);
                serviEncontrado = servi;
                break;
            }
            index++;
        }
        if (serviEncontrado != null) {
            Seccion sec;
            sec = new Seccion(txt_sec_srv_edit.getText());
            Despacho desp;
            desp = new Despacho(txt_desp_srv_edit.getText());
            try {
                Date fincor = new SimpleDateFormat("dd/MM/yyyy").parse(txt_incor_srv_edit.getText());
                String idEditar = txt_id_edit.getText();
                String nomEditar = txt_nomb_edit.getText();
                String apeEditar = txt_apell_edit.getText();
                String estCivil = txt_ecivil_edit.getText();
                //(Departamento , Despacho , Date fechaIncor,  id,  nombre,  apellido,  eCivil
                dbEmpServicio.set(index, new Servicio(sec, desp, fincor, idEditar, nomEditar, apeEditar, estCivil));
                JOptionPane.showMessageDialog(rootPane, "Profesor Editado Correctamente");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error, verifique que la fecha u otros campos estén correctos" + e);
            }
        }
        limpiar();
    }//GEN-LAST:event_txt_sec_srvActionPerformed

    private void btn_agregar_srvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_srvActionPerformed
        // TODO add your handling code here:
        Servicio serv = null;
        try {
            String nombre = txt_nom_srv.getText();
            String apellido = txt_ape_srv.getText();
            String cedula = txt_id_srv.getText();
            String ecivil = txt_ecivil_srv.getText();
            Date fechaIncorp = new SimpleDateFormat("dd/MM/yyyy").parse(txt_incor_srv.getText());
            Seccion sec = new Seccion(txt_sec_srv.getText());
            Despacho despacho = new Despacho(txt_desp_srv.getText());
            if (!"".equals(nombre) && !"".equals(apellido) && !"".equals(cedula) && !"".equals(ecivil)) {
                //Profesor(Departamento depto, Despacho despacho, Date fechaIncor, String id, String nombre, String apellido, String eCivil, despacho, fechaIncor, id, nombre, apellido, eCivil);
                serv = new Servicio(sec, despacho, fechaIncorp, cedula, nombre, apellido, ecivil);
            }
            if (addDbEmServicio(serv)) {
                JOptionPane.showMessageDialog(rootPane, "Empleado guardado");
                limpiar();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede guardar");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error, verifique que la fecha u otros campos estén correctos\n" + e);
        }
    }//GEN-LAST:event_btn_agregar_srvActionPerformed

    private void btn_limpiar_srvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiar_srvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_limpiar_srvActionPerformed

    private void btn_listarSrvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listarSrvActionPerformed
        ArrayList<Servicio> datosServicio = listarServicio();
        DefaultTableModel model;
        //Departamento depto, Despacho despacho, Date fechaIncor, String id, String nombre, String apellido, String eCivil
        String[] columnas = {"id", "nombre", "apellido", "eCivil", "seccion", "desp", "incorp"};
        model = new DefaultTableModel(null, columnas);
        String[] filas = new String[7];
        for (Servicio serv : datosServicio) {
            filas[0] = serv.getId();
            filas[1] = serv.getNombre();
            filas[2] = serv.getApellido();
            filas[3] = serv.geteCivil();
            filas[4] = serv.devolverSec();
            filas[5] = serv.devolverDesp();
            filas[6] = String.valueOf(serv.getFechaIncor());
            model.addRow(filas);
        }
        tbl_tablaSrv.setModel(model);
    }//GEN-LAST:event_btn_listarSrvActionPerformed

    private void txt_sec_srv_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sec_srv_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sec_srv_editActionPerformed

    private void btn_busca_srv_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_busca_srv_EditActionPerformed
        Servicio serviEncontrado = null;
        String cedBuscar = txt_id_srv_edit.getText();
        for (Servicio servi : dbEmpServicio) {
            if (servi.getId().equals(cedBuscar)) {
                serviEncontrado = servi;
                break;
            }
        }
        if (serviEncontrado != null) {
            txt_ape_srv_edit.setText(serviEncontrado.getApellido());
            txt_sec_srv_edit.setText(serviEncontrado.devolverSec());
            txt_desp_srv_edit.setText(serviEncontrado.devolverDesp());
            txt_ecivil_srv_edit.setText(serviEncontrado.geteCivil());
            txt_nom_srv_edit.setText(serviEncontrado.getNombre());
            txt_incor_srv_edit.setText(String.valueOf(serviEncontrado.getFechaIncor()));
        } else {
            JOptionPane.showMessageDialog(rootPane, "No se encuentra ese id");
        }


    }//GEN-LAST:event_btn_busca_srv_EditActionPerformed

    private void btn_editar_srvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editar_srvActionPerformed
        int index = 0;
        Servicio serviEncontrado = null;
        String cedBuscar = txt_id_srv_edit.getText();
        for (Servicio servi : dbEmpServicio) {
            if (servi.getId().equals(cedBuscar)) {
                System.out.println(index);
                serviEncontrado = servi;
                break;
            }
            index++;
        }
        if (serviEncontrado != null) {
            Seccion sec;
            sec = new Seccion(txt_sec_srv_edit.getText());
            Despacho desp;
            desp = new Despacho(txt_desp_srv_edit.getText());
            try {
                Date fincor = new SimpleDateFormat("dd/MM/yyyy").parse(txt_incor_srv_edit.getText());
                String idEditar = txt_id_srv_edit.getText();
                String nomEditar = txt_nom_srv_edit.getText();
                String apeEditar = txt_ape_srv_edit.getText();
                String estCivil = txt_ecivil_srv_edit.getText();
                //(Seccion , Despacho , Date fechaIncor,  id,  nombre,  apellido,  eCivil
                dbEmpServicio.set(index, new Servicio(sec, desp, fincor, idEditar, nomEditar, apeEditar, estCivil));
                JOptionPane.showMessageDialog(rootPane, "Empleado Editado Correctamente");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error, verifique que la fecha u otros campos estén correctos" + e);
            }
        }
        limpiar();
    }//GEN-LAST:event_btn_editar_srvActionPerformed

    private void btn_limpiar_edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiar_edit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_limpiar_edit1ActionPerformed

    private void btn_agregarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarEstActionPerformed
        // TODO add your handling code here:
        Estudiante est = null;
        try {
            String nombre = txt_nombEst.getText();
            String apellido = txt_apellEst.getText();
            String cedula = txt_idEst.getText();
            String ecivil = txt_ecivilEst.getText();
            //Date fechaIncorp = new SimpleDateFormat("dd/MM/yyyy").parse(txt_incor.getText());
            Curso curso = new Curso(txt_cursoEst.getText());
            if (!"".equals(nombre) && !"".equals(apellido) && !"".equals(cedula) && !"".equals(ecivil) && !"".equals(curso.getNombreCurso())) {
                //Profesor(Departamento depto, Despacho despacho, Date fechaIncor, String id, String nombre, String apellido, String eCivil, despacho, fechaIncor, id, nombre, apellido, eCivil);
                est = new Estudiante(curso, cedula, nombre, apellido, ecivil);
            }
            if (addDbEstudiante(est)) {
                JOptionPane.showMessageDialog(rootPane, "Estudiante guardado");
                limpiar();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede guardar");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error, verifique los campos estén correctos" + e);
        }

    }//GEN-LAST:event_btn_agregarEstActionPerformed

    private void btn_limpiarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarEstActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btn_limpiarEstActionPerformed

    private void btn_listarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listarEstActionPerformed
        // TODO add your handling code here:
        ArrayList<Estudiante> datosEstudiante = listarEstudiante();
        DefaultTableModel model;
        //Departamento depto, Despacho despacho, Date fechaIncor, String id, String nombre, String apellido, String eCivil
        String[] columnas = {"id", "nombre", "apellido", "eCivil", "curso"};
        model = new DefaultTableModel(null, columnas);
        String[] filas = new String[5];
        for (Estudiante est : datosEstudiante) {
            filas[0] = est.getId();
            filas[1] = est.getNombre();
            filas[2] = est.getApellido();
            filas[3] = est.geteCivil();
            filas[4] = est.devolverCurso();
            model.addRow(filas);
        }
        tbl_tablaEst.setModel(model);
    }//GEN-LAST:event_btn_listarEstActionPerformed

    private void btn_buscaEst_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscaEst_editActionPerformed
        Estudiante estEncontrado = null;
        String cedBuscar = txt_idEst_edit.getText();
        for (Estudiante est : dbEstudiantes) {
            if (est.getId().equals(cedBuscar)) {
                estEncontrado = est;
                break;
            }
        }
        if (estEncontrado != null) {
            txt_apellEst_edit.setText(estEncontrado.getApellido());
            txt_cursoEst_edit.setText(estEncontrado.devolverCurso());
            txt_ecivilEst_edit.setText(estEncontrado.geteCivil());
            txt_nombEst_edit.setText(estEncontrado.getNombre());
        } else {
            JOptionPane.showMessageDialog(rootPane, "No se encuentra ese id");
        }
    }//GEN-LAST:event_btn_buscaEst_editActionPerformed

    private void btn_editarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarEstActionPerformed
        int index = 0;
        Estudiante estEncontrado = null;
        String cedBuscar = txt_idEst_edit.getText();
        for (Estudiante est : dbEstudiantes) {
            if (est.getId().equals(cedBuscar)) {
                System.out.println(index);
                estEncontrado = est;
                break;
            }
            index++;
        }
        if (estEncontrado != null) {
            Curso curso;
            curso = new Curso(txt_cursoEst_edit.getText());
            try {
                //Date fincor = new SimpleDateFormat("dd/MM/yyyy").parse(txt_incor_srv_edit.getText());
                String idEditar = txt_idEst_edit.getText();
                String nomEditar = txt_nombEst_edit.getText();
                String apeEditar = txt_apellEst_edit.getText();
                String estCivil = txt_ecivilEst_edit.getText();
                //Curso curso, String id, String nombre, String apellido, String eCivil
                dbEstudiantes.set(index, new Estudiante(curso, idEditar, nomEditar, apeEditar, estCivil));
                JOptionPane.showMessageDialog(rootPane, "Estudiante Editado Correctamente");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error, verifique que los campos estén correctos" + e);
            }
        }
        limpiar();
    }//GEN-LAST:event_btn_editarEstActionPerformed

    private void btn_limpiar_edit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiar_edit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_limpiar_edit2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFacultad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFacultad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFacultad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFacultad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFacultad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_agregarEst;
    private javax.swing.JButton btn_agregar_srv;
    private javax.swing.JButton btn_buscaEdit;
    private javax.swing.JButton btn_buscaEst_edit;
    private javax.swing.JButton btn_busca_srv_Edit;
    private javax.swing.JButton btn_editarEst;
    private javax.swing.JButton btn_editarProfe;
    private javax.swing.JButton btn_editar_srv;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_limpiarEst;
    private javax.swing.JButton btn_limpiar_edit;
    private javax.swing.JButton btn_limpiar_edit1;
    private javax.swing.JButton btn_limpiar_edit2;
    private javax.swing.JButton btn_limpiar_srv;
    private javax.swing.JButton btn_listarEst;
    private javax.swing.JButton btn_listarProfe;
    private javax.swing.JButton btn_listarSrv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbl_tabla;
    private javax.swing.JTable tbl_tablaEst;
    private javax.swing.JTable tbl_tablaSrv;
    private javax.swing.JTextField txt_ape_srv;
    private javax.swing.JTextField txt_ape_srv_edit;
    private javax.swing.JTextField txt_apell;
    private javax.swing.JTextField txt_apellEst;
    private javax.swing.JTextField txt_apellEst_edit;
    private javax.swing.JTextField txt_apell_edit;
    private javax.swing.JTextField txt_cursoEst;
    private javax.swing.JTextField txt_cursoEst_edit;
    private javax.swing.JTextField txt_depto;
    private javax.swing.JTextField txt_depto_edit;
    private javax.swing.JTextField txt_desp;
    private javax.swing.JTextField txt_desp_edit;
    private javax.swing.JTextField txt_desp_srv;
    private javax.swing.JTextField txt_desp_srv_edit;
    private javax.swing.JTextField txt_ecivil;
    private javax.swing.JTextField txt_ecivilEst;
    private javax.swing.JTextField txt_ecivilEst_edit;
    private javax.swing.JTextField txt_ecivil_edit;
    private javax.swing.JTextField txt_ecivil_srv;
    private javax.swing.JTextField txt_ecivil_srv_edit;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_idEst;
    private javax.swing.JTextField txt_idEst_edit;
    private javax.swing.JTextField txt_id_edit;
    private javax.swing.JTextField txt_id_srv;
    private javax.swing.JTextField txt_id_srv_edit;
    private javax.swing.JTextField txt_incor;
    private javax.swing.JTextField txt_incor_edit;
    private javax.swing.JTextField txt_incor_srv;
    private javax.swing.JTextField txt_incor_srv_edit;
    private javax.swing.JTextField txt_nom_srv;
    private javax.swing.JTextField txt_nom_srv_edit;
    private javax.swing.JTextField txt_nomb;
    private javax.swing.JTextField txt_nombEst;
    private javax.swing.JTextField txt_nombEst_edit;
    private javax.swing.JTextField txt_nomb_edit;
    private javax.swing.JTextField txt_sec_srv;
    private javax.swing.JTextField txt_sec_srv_edit;
    // End of variables declaration//GEN-END:variables
}
